# KNN

 K-NN algorithm assumes the similarity between the new case/data and available cases and put the new case into the category
that is most similar to the available categories.

- K-NN algorithm stores all the available data and classifies a new data point based on the similarity. This means when
new data appears then it can be easily classified into a well suite category by using K- NN algorithm.

- Euclidean distance = sq.root((x2-x1)sq + (y2-y1)sq)

In [2]:
# importing required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [3]:
# Reading the dataset (csv file)
df = pd.read_csv("loan_prediction.csv")

In [4]:
# Visualizing 1st 5 rows
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [5]:
# Finding shape
df.shape

(614, 13)

In [6]:
# Descriptive stats
df.describe(include='all')

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
count,614,601,611,599,614,582,614.000000,614.000000,592.000000,600.00000,564.000000,614,614
unique,614,2,2,4,2,2,NaN,NaN,NaN,NaN,NaN,3,2
top,LP001002,Male,Yes,0,Graduate,No,NaN,NaN,NaN,NaN,NaN,Semiurban,Y
freq,1,489,398,345,480,500,NaN,NaN,NaN,NaN,NaN,233,422
mean,NaN,NaN,NaN,NaN,NaN,NaN,5403.459283,1621.245798,146.412162,342.00000,0.842199,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,6109.041673,2926.248369,85.587325,65.12041,0.364878,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,150.000000,0.000000,9.000000,12.00000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2877.500000,0.000000,100.000000,360.00000,1.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,3812.500000,1188.500000,128.000000,360.00000,1.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,5795.000000,2297.250000,168.000000,360.00000,1.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,81000.000000,41667.000000,700.000000,480.00000,1.000000,NaN,NaN

In [7]:
# Finding for null values
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
# Removing unwanted columns
df.drop(columns=['Loan_ID','Gender','Dependents','Self_Employed'],inplace=True)

In [9]:
# Handling null values
df['Credit_History'].fillna(df['Credit_History'].mean(),inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mean(),inplace=True)
df['LoanAmount'].fillna(df['LoanAmount'].mean(),inplace=True)
df['Married'].fillna("Yes",inplace=True)

In [10]:
df.isnull().sum()

Married              0
Education            0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [11]:
# Checking data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Married            614 non-null    object
 1   Education          614 non-null    object
 2   ApplicantIncome    614 non-null    int64
 3   CoapplicantIncome  614 non-null    float64
 4   LoanAmount         614 non-null    float64
 5   Loan_Amount_Term   614 non-null    float64
 6   Credit_History     614 non-null    float64
 7   Property_Area      614 non-null    object
 8   Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(4)
memory usage: 43.3+ KB

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
# Encoding
le = LabelEncoder()

df['Married'] = le.fit_transform(df['Married'])
df['Education'] = le.fit_transform(df['Education'])
df['Property_Area'] = le.fit_transform(df['Property_Area'])

In [14]:
# Spliting dependent and independent variable
x = df.drop('Loan_Status',axis=1)
y = df['Loan_Status']

In [15]:
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler()

In [16]:
scaled_x=pd.DataFrame(scale.fit_transform(x),columns=x.columns)

In [17]:
# Spliting data for train and test
x_train,x_test,y_train,y_test = train_test_split(scaled_x,y,test_size=0.2,random_state=12)

Model Building Using KNN

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
Knn=KNeighborsClassifier()

In [23]:
Knn.fit(x_train,y_train)

KNeighborsClassifier()

In [26]:
#Testing the model
Pred=Knn.predict(x_test)
Pred

array(['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y',
       'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'N', 'N', 'N'], dtype=object)

In [27]:
df

,Married,Education,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,0,5849,0.0,146.412162,360.0,1.0,2,Y
1,1,0,4583,1508.0,128.000000,360.0,1.0,0,N
2,1,0,3000,0.0,66.000000,360.0,1.0,2,Y
3,1,1,2583,2358.0,120.000000,360.0,1.0,2,Y
4,0,0,6000,0.0,141.000000,360.0,1.0,2,Y
...,...,...,...,...,...,...,...,...,...
609,0,0,2900,0.0,71.000000,360.0,1.0,0,Y
610,1,0,4106,0.0,40.000000,180.0,1.0,0,Y
611,1,0,8072,240.0,253.000000,360.0,1.0,2,Y
612,1,0,7583,0.0,187.000000,360.0,1.0,2,Y
613,0,0,4583,0.0,133.000000,360.0,0.0,1,N

In [29]:
Knn.predict([[0,0,5849,0.0,146.412162,360.0,1.0,2]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array(['Y'], dtype=object)

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(y_test,pred)

0.8211382113821138

In [32]:
print("Shape of scaled_x:", scaled_x.shape)
print("Shape of y_train:", y_train.shape)

Shape of scaled_x: (614, 8)
Shape of y_train: (491,)

In [33]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
param_grid = {'n_neighbors': [3, 5, 7, 9], 'p': [1, 2]}
grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5)
grid_search.fit(x_train, y_train)
best_knn = grid_search.best_estimator_

# Predictions
pred = best_knn.predict(x_test)

# Evaluate accuracy
accuracy = accuracy_score(y_test, pred)
print("Accuracy:", accuracy)

Accuracy: 0.8211382113821138